#!/bin/bash

PROJECT_NAME=yt-player
BASE_DIR=/var/slothyx
TMP_DIR=$BASE_DIR/tmp
RELEASE_DIR=$BASE_DIR/$PROJECT_NAME
DEV_DIR=$BASE_DIR/$PROJECT_NAME-dev
LOG_FILE=$BASE_DIR/$PROJECT_NAME.log
REPOSITORY=/opt/git/repositories/$PROJECT_NAME.git

exec 1>$LOG_FILE
exec 2>&1

function checkoutRepo {
        branch="$1"
        targetDir="$2"

        cd $TMP_DIR

        echo "Cloning branch ${branch}..."
        unset GIT_DIR
        git clone -b $branch $REPOSITORY $branch

        echo "Running build script..."
        cd "$branch"
        chmod a+x build.sh
        ./build.sh

        echo "Searching built data..."
        if [ -d "out/www" ]; then
                echo "www-folder detected!"
                rm -rf "$targetDir"
                cp -rf "out/www" "$targetDir"
                chmod -R a+rx "$targetDir"
        fi

        cd ..
        echo "Cleanup..."
        rm -rf $branch
}

function thirdElementOf {
        string="$1"
        delimiter="$2"
        args=(${string//"${delimiter}"/ })
        echo "${args[2]}"
}

while read line
do
        ref="$(thirdElementOf "$line" " ")"
        branch="$(thirdElementOf "$ref" "/")"
done < /dev/stdin

if [ "$branch" == "release" ]; then
        echo "New Release detected!"
        checkoutRepo "$branch" "$RELEASE_DIR"
fi
if [ "$branch" == "master" ]; then
        echo "New Dev-version detected!"
        checkoutRepo "$branch" "$DEV_DIR"
fi
